packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  msgpackr-extract: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1112.0'
  - '@aws-sdk/s3-request-presigner@3.1112.0'

settings:
  onlyBuiltDependencies:
    - "@prisma/client"
    - "@prisma/engines"
    - "@scarf/scarf"
    - "argon2"
    - "esbuild"
    - "prisma"
    - "sharp"
    - "unrs-resolver"
