export const permissionLabels: Record<string, string> = {
  'products:read': 'Productos: ver',
  'products:write': 'Productos: editar',
  'categories:read': 'Categorías: ver',
  'categories:write': 'Categorías: editar',
  'stock:read': 'Stock: ver',
  'stock:write': 'Stock: editar',
  'variants:read': 'Variantes: ver',
  'variants:write': 'Variantes: editar',
  'orders:read': 'Pedidos: ver',
  'orders:write': 'Pedidos: editar',
  'customers:read': 'Clientes: ver',
  'customers:write': 'Clientes: editar',
  'coupons:read': 'Cupones: ver',
  'coupons:write': 'Cupones: editar',
  'store_config:read': 'Config: ver',
  'store_config:write': 'Config: editar',
  'shipping_options:read': 'Envíos: ver',
  'shipping_options:write': 'Envíos: editar',
  'currencies:read': 'Monedas: ver',
  'currencies:write': 'Monedas: editar',
  'assets:read': 'Assets: ver',
  'assets:write': 'Assets: editar',
  'pages:read': 'Páginas: ver',
  'pages:write': 'Páginas: editar',
  'reviews:moderate': 'Reseñas: moderar',
  'production:read': 'Producción: ver',
  'production:write': 'Producción: editar',
  'custom_designs:read': 'Diseños: ver',
  'custom_designs:write': 'Diseños: editar',
  'users:read': 'Usuarios: ver',
  'users:write': 'Usuarios: editar',
  'roles:read': 'Roles: ver',
  'roles:write': 'Roles: editar',
  'analytics:read': 'Analytics: ver',
  'audit_logs:read': 'Audit logs: ver',
  'exports:read': 'Exportar',
  'dashboard:read': 'Dashboard: ver',
  'backups:write': 'Backups: ejecutar',
  'queues:read': 'Colas: ver',
  'queues:write': 'Colas: editar',
  'shipments:read': 'Envíos de orden: ver',
  'shipments:write': 'Envíos de orden: editar',
};

export const defaultNewUserPermissions = [
  'dashboard:read',
  'orders:read',
  'products:read',
  'categories:read',
];

export const allPermissions = Object.keys(permissionLabels);
